### ISSUE TITLE
BUG: Uncaught TypeError: Cannot read properties of null (reading 'data')

### ISSUE THREAD

**Issue by devinat1** [MichaBrugger/obsidian-footnotes#39]
Uncaught TypeError: Cannot read properties of null (reading 'data')
    at Autocomplete.onTrigger (plugin:obsidian-footnotes:380:20)
    at t.trigger (app.js:1:1600741)
    at e.trigger (app.js:1:2116834)
    at app.js:1:1388638
    at l (app.js:1:260204)
    
This happened as I was writing on a note without any footnotes.

![image](https://github.com/MichaBrugger/obsidian-footnotes/assets/15788108/f5ef1abf-13c2-472c-8439-e31fa4fa30d7)

## System Info
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.4.16
	Operating system: Windows 10 Home 10.0.26090
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: Minimal v7.5.4
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 56
	Plugins enabled: 34
		1: Templater v2.2.3
		2: Tab Switcher v1.4.0
		3: Google Photos v1.6.5
		4: Dataview v0.5.66
		5: Editor Syntax Highlight v0.1.3
		6: Minimal Theme Settings v7.5.0
		7: Commander v0.5.1
		8: Canvas Mindmap v0.1.9
		9: Auto Link Title v1.5.3
		10: Admonition v10.2.0
		11: Simple CanvaSearch v0.1.0
		12: QuickAdd v1.8.1
		13: Excalidraw v2.1.1
		14: Todoist Sync v1.12.0
		15: Linter v1.23.2
		16: Readwise Official v2.0.1
		17: Enhancing Export v1.10.4
		18: Zotero Integration v3.1.7
		19: Paste URL into selection v1.7.0
		20: Note Refactor v1.8.2
		21: Canvas Filter v0.9.4
		22: Ghost Fade Focus v3.0.0
		23: WakaTime v1.0.0
		24: Quick Switcher++ v4.0.0
		25: Recent Files v1.3.10
		26: ExcaliBrain v0.2.15
		27: Projects v1.17.2
		28: Periodic Notes v0.0.17
		29: Homepage v3.8.0
		30: Calendar v1.5.10
		31: Longform v2.0.7
		32: BRAT v1.0.1
		33: Slides Extended v2.0.5
		34: Footnote Shortcut v0.1.3

**Comment by Comprehensive-Jason** [comment]
Thanks for reporting! I suspect this bug has to do with the autosuggest feature of the function, which has been removed in master because Obsidian now has a native footnote autosuggest. Thus, this problem should no longer exist once the new version rolls out.
